### ISSUE TITLE
tailwind version

### ISSUE THREAD

**Issue by caketogo** [flatanimals/gusts#1]
Hi
Have you considered having the function to change the version of tailwind thats getting used?
Maybe a dropdown?

Also how about been able to save the html?

Maybe also make the rightside of the view fixed so you can always see the output?

Very useful tool by the way,...

**Comment by virkillz** [comment]
I submit a PR to upgrade to v.1.0.1

Just in case its not being merged, it's in my repo:
https://github.com/virkillz/gusts
